# Generated by Django 3.2.20 on 2023-07-20 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_booklanduser_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booklanduser',
            name='profile_picture',
            field=models.URLField(blank=True, null=True),
        ),
    ]
