# Generated by Django 3.2.20 on 2023-08-07 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_booklanduser_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booklanduser',
            name='gender',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
    ]
