# Generated by Django 3.2.20 on 2023-08-10 15:37

import Bookland.accounts.validators
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_booklanduser_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booklanduser',
            name='first_name',
            field=models.CharField(max_length=15, validators=[django.core.validators.MinLengthValidator(2), Bookland.accounts.validators.validate_only_alphabetical, Bookland.accounts.validators.upper_first_letter]),
        ),
        migrations.AlterField(
            model_name='booklanduser',
            name='last_name',
            field=models.CharField(max_length=15, validators=[django.core.validators.MinLengthValidator(2), Bookland.accounts.validators.validate_only_alphabetical, Bookland.accounts.validators.upper_first_letter]),
        ),
    ]
