# Generated by Django 3.2.20 on 2023-08-11 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20230810_1737'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booklanduser',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='mediafiles/profile_photos/'),
        ),
    ]
