# Generated by Django 3.2.20 on 2023-08-11 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_booklanduser_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booklanduser',
            name='profile_picture',
            field=models.ImageField(default='/static/images/profile_image.jpg', upload_to='mediafiles/profile_photos/'),
        ),
    ]
