# Generated by Django 3.2.20 on 2023-08-11 11:08

import Bookland.accounts.validators
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_booklanduser_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booklanduser',
            name='first_name',
            field=models.CharField(blank=True, max_length=15, null=True, validators=[django.core.validators.MinLengthValidator(2), Bookland.accounts.validators.validate_only_alphabetical, Bookland.accounts.validators.upper_first_letter]),
        ),
        migrations.AlterField(
            model_name='booklanduser',
            name='last_name',
            field=models.CharField(blank=True, max_length=15, null=True, validators=[django.core.validators.MinLengthValidator(2), Bookland.accounts.validators.validate_only_alphabetical, Bookland.accounts.validators.upper_first_letter]),
        ),
        migrations.AlterField(
            model_name='booklanduser',
            name='profile_picture',
            field=models.ImageField(upload_to='mediafiles/profile_photos/'),
        ),
    ]
