# Generated by Django 3.2.20 on 2023-08-11 16:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_auto_20230811_1308'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booklanduser',
            name='address',
        ),
        migrations.RemoveField(
            model_name='booklanduser',
            name='phone_number',
        ),
    ]
