# Generated by Django 3.2.20 on 2023-08-08 04:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Bookmark',
        ),
    ]
