# Generated by Django 3.2.20 on 2023-07-20 17:26

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('authors', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('price', models.FloatField(validators=[django.core.validators.MinValueValidator(1)])),
                ('genre', models.CharField(choices=[('Romance', 'Romance'), ('Fantasy', 'Fantasy'), ('Criminal', 'Criminal'), ('Historical novel', 'Historical novel'), ('Thriller', 'Thriller'), ('Science fiction', 'Science fiction'), ('Poetry', 'Poetry'), ('Biography/autobiography', 'Biography/autobiography'), ('Health', 'Health'), ('Psychology', 'Psychology'), ('Esoteric', 'Esoteric'), ('Home, Family, Hobby', 'Home, Family, Hobby'), ("Children's literature", "Children's literature"), ('Other', 'Other')], max_length=23)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authors.author')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
