# Generated by Django 3.2.20 on 2023-07-21 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_book_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='book_photo',
            field=models.URLField(default=None),
            preserve_default=False,
        ),
    ]
