# Generated by Django 3.2.20 on 2023-07-25 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_book_book_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='book',
            name='genre',
        ),
        migrations.AddField(
            model_name='book',
            name='genre',
            field=models.ManyToManyField(choices=[('Romance', 'Romance'), ('Fantasy', 'Fantasy'), ('Criminal', 'Criminal'), ('Historical novel', 'Historical novel'), ('Thriller', 'Thriller'), ('Science fiction', 'Science fiction'), ('Poetry', 'Poetry'), ('Biography/autobiography', 'Biography/autobiography'), ('Health', 'Health'), ('Psychology', 'Psychology'), ('Esoteric', 'Esoteric'), ('Home, Family, Hobby', 'Home, Family, Hobby'), ("Children's literature", "Children's literature"), ('Other', 'Other')], max_length=23, to='books.Genre'),
        ),
    ]
