# Generated by Django 3.2.20 on 2023-07-25 08:01

from django.db import migrations, models


class Migration(migrations.Migration):
    atomic = False

    dependencies = [
        ('books', '0005_auto_20230725_0956'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Genre',
            new_name='Category',
        ),
        migrations.RemoveField(
            model_name='book',
            name='genre',
        ),
        migrations.AddField(
            model_name='book',
            name='category',
            field=models.ManyToManyField(choices=[('Romance', 'Romance'), ('Fantasy', 'Fantasy'), ('Criminal', 'Criminal'), ('Historical novel', 'Historical novel'), ('Thriller', 'Thriller'), ('Science fiction', 'Science fiction'), ('Poetry', 'Poetry'), ('Biography/autobiography', 'Biography/autobiography'), ('Health', 'Health'), ('Psychology', 'Psychology'), ('Esoteric', 'Esoteric'), ('Home, Family, Hobby', 'Home, Family, Hobby'), ("Children's literature", "Children's literature"), ('Other', 'Other')], max_length=23, to='books.Category'),
        ),
    ]
