# Generated by Django 3.2.20 on 2023-07-25 08:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0006_auto_20230725_1001'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='category',
        ),
        migrations.AddField(
            model_name='book',
            name='category',
            field=models.ForeignKey(default=None, max_length=23, on_delete=django.db.models.deletion.CASCADE, to='books.category'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(choices=[('Romance', 'Romance'), ('Fantasy', 'Fantasy'), ('Criminal', 'Criminal'), ('Historical novel', 'Historical novel'), ('Thriller', 'Thriller'), ('Science fiction', 'Science fiction'), ('Poetry', 'Poetry'), ('Biography/autobiography', 'Biography/autobiography'), ('Health', 'Health'), ('Psychology', 'Psychology'), ('Esoteric', 'Esoteric'), ('Home, Family, Hobby', 'Home, Family, Hobby'), ("Children's literature", "Children's literature"), ('Other', 'Other')], max_length=100),
        ),
    ]
