# Generated by Django 3.2.20 on 2023-07-28 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0010_book_condition'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='book_photo',
            field=models.ImageField(upload_to='book_photos/'),
        ),
    ]
