# Generated by Django 3.2.20 on 2023-07-28 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0011_alter_book_book_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='book_photo',
            field=models.ImageField(upload_to='mediafiles/book_photos/'),
        ),
    ]
