# Generated by Django 3.2.20 on 2023-07-30 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0012_alter_book_book_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='condition',
            field=models.CharField(blank=True, choices=[('', '-------'), ('Perfect', 'Perfect'), ('Good', 'Good'), ('Not very good', 'Not very good')], default='', max_length=13),
        ),
    ]
