# Generated by Django 3.2.20 on 2023-07-30 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0013_alter_book_condition'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='upload_date',
            field=models.DateTimeField(auto_now_add=True, default='2023-07-15 14:30:00'),
            preserve_default=False,
        ),
    ]
