# Generated by Django 3.2.20 on 2023-07-30 15:22

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0014_book_upload_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='upload_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
