# Generated by Django 3.2.20 on 2023-08-08 04:47

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('books', '0016_bookmark'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Bookmark',
            new_name='MyList',
        ),
    ]
