# Generated by Django 3.2.20 on 2023-08-08 16:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0017_rename_bookmark_mylist'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Category',
        ),
    ]
