# Generated by Django 3.2.20 on 2023-08-11 16:17

import Bookland.accounts.validators
import Bookland.books.validators
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0021_purchase'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='address_for_delivery',
            field=models.CharField(default='London, London Street 55, 546543', max_length=150),
        ),
        migrations.AddField(
            model_name='purchase',
            name='delivery_method',
            field=models.CharField(choices=[('FedEx', 'FedEx'), ('DHL', 'DHL'), ('UPS', 'UPS')], default='DHL', max_length=5),
        ),
        migrations.AddField(
            model_name='purchase',
            name='first_name',
            field=models.CharField(default='Mariq', max_length=50, validators=[django.core.validators.MinLengthValidator(2), Bookland.accounts.validators.validate_only_alphabetical, Bookland.accounts.validators.upper_first_letter]),
        ),
        migrations.AddField(
            model_name='purchase',
            name='last_name',
            field=models.CharField(default='Petrova', max_length=50, validators=[django.core.validators.MinLengthValidator(2), Bookland.accounts.validators.validate_only_alphabetical, Bookland.accounts.validators.upper_first_letter]),
        ),
        migrations.AddField(
            model_name='purchase',
            name='payment_method',
            field=models.CharField(choices=[('Cash on Delivery', 'Cash on Delivery')], default='Cash on Delivery', max_length=16),
        ),
        migrations.AddField(
            model_name='purchase',
            name='phone_number',
            field=models.CharField(default='+6599890006121', max_length=14, validators=[django.core.validators.MinValueValidator(14), Bookland.books.validators.start_with_plus]),
        ),
    ]
